package com.dxc.fs.oc.csrportal.withdrawals;


/**
 * This class was automatically generated by the data modeler tool.
 */

public class surrender_response_list implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.dxc.fs.oc.drools.model.ProcessingSurrenderResponse> response_list;

	public surrender_response_list() {
	this.response_list = new java.util.ArrayList<com.dxc.fs.oc.drools.model.ProcessingSurrenderResponse>();
	              
	
	    
	}

	public java.util.List<com.dxc.fs.oc.drools.model.ProcessingSurrenderResponse> getResponse_list() {
		return this.response_list;
	}

	public void setResponse_list(
			java.util.List<com.dxc.fs.oc.drools.model.ProcessingSurrenderResponse> response_list) {
		this.response_list = response_list;
	}

	public surrender_response_list(
			java.util.List<com.dxc.fs.oc.drools.model.ProcessingSurrenderResponse> response_list) {
		this.response_list = response_list;
	}

}